#! /usr/bin/python3.8

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'karnaugh.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import Karnaugh as karnaugh
import re


class Ui_Karnaugh(object):
    def setupUi(self, Karnaugh):
        Karnaugh.setObjectName("Karnaugh")
        Karnaugh.resize(897, 505)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("k.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Karnaugh.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Karnaugh)
        self.centralwidget.setObjectName("centralwidget")
        self.btnA = QtWidgets.QPushButton(self.centralwidget)
        self.btnA.setGeometry(QtCore.QRect(30, 280, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnA.setFont(font)
        self.btnA.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnA.setFlat(False)
        self.btnA.setObjectName("btnA")
        self.btnB = QtWidgets.QPushButton(self.centralwidget)
        self.btnB.setGeometry(QtCore.QRect(90, 280, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnB.setFont(font)
        self.btnB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnB.setObjectName("btnB")
        self.btnC = QtWidgets.QPushButton(self.centralwidget)
        self.btnC.setGeometry(QtCore.QRect(150, 280, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnC.setFont(font)
        self.btnC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnC.setObjectName("btnC")
        self.btnD = QtWidgets.QPushButton(self.centralwidget)
        self.btnD.setGeometry(QtCore.QRect(210, 280, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnD.setFont(font)
        self.btnD.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnD.setObjectName("btnD")
        self.btnCalc = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalc.setGeometry(QtCore.QRect(30, 350, 111, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 211, 211, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.btnCalc.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCalc.setFont(font)
        self.btnCalc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCalc.setAutoFillBackground(False)
        self.btnCalc.setObjectName("btnCalc")
        self.btnPlus = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlus.setGeometry(QtCore.QRect(290, 280, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnPlus.setFont(font)
        self.btnPlus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPlus.setObjectName("btnPlus")
        self.lblInput = QtWidgets.QLabel(self.centralwidget)
        self.lblInput.setGeometry(QtCore.QRect(30, 150, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblInput.setFont(font)
        self.lblInput.setFrameShape(QtWidgets.QFrame.Box)
        self.lblInput.setText("")
        self.lblInput.setObjectName("lblInput")
        self.lblInput_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblInput_2.setGeometry(QtCore.QRect(470, 150, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblInput_2.setFont(font)
        self.lblInput_2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblInput_2.setText("")
        self.lblInput_2.setObjectName("lblInput_2")
        self.lblHead1 = QtWidgets.QLabel(self.centralwidget)
        self.lblHead1.setGeometry(QtCore.QRect(30, 110, 100, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.lblHead1.setFont(font)
        self.lblHead1.setObjectName("lblHead1")
        self.lblHead2 = QtWidgets.QLabel(self.centralwidget)
        self.lblHead2.setGeometry(QtCore.QRect(470, 110, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.lblHead2.setFont(font)
        self.lblHead2.setObjectName("lblHead2")
        self.dvd1 = QtWidgets.QFrame(self.centralwidget)
        self.dvd1.setGeometry(QtCore.QRect(445, 115, 3, 355))
        self.dvd1.setFrameShape(QtWidgets.QFrame.VLine)
        self.dvd1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dvd1.setObjectName("dvd1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(530, 260, 211, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid1 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid1.setContentsMargins(0, 0, 0, 0)
        self.grid1.setObjectName("grid1")
        self.lbl30 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl30.setFont(font)
        self.lbl30.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl30.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl30.setObjectName("lbl30")
        self.grid1.addWidget(self.lbl30, 3, 0, 1, 1)
        self.lbl02 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl02.setFont(font)
        self.lbl02.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl02.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl02.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl02.setObjectName("lbl02")
        self.grid1.addWidget(self.lbl02, 0, 2, 1, 1)
        self.lbl01 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl01.setFont(font)
        self.lbl01.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl01.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl01.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl01.setObjectName("lbl01")
        self.grid1.addWidget(self.lbl01, 0, 1, 1, 1)
        self.lbl11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl11.setFont(font)
        self.lbl11.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl11.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl11.setObjectName("lbl11")
        self.grid1.addWidget(self.lbl11, 1, 1, 1, 1)
        self.lbl33 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl33.setFont(font)
        self.lbl33.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl33.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl33.setObjectName("lbl33")
        self.grid1.addWidget(self.lbl33, 3, 3, 1, 1)
        self.lbl13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl13.setFont(font)
        self.lbl13.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl13.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl13.setObjectName("lbl13")
        self.grid1.addWidget(self.lbl13, 1, 3, 1, 1)
        self.lbl20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl20.setFont(font)
        self.lbl20.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl20.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl20.setObjectName("lbl20")
        self.grid1.addWidget(self.lbl20, 2, 0, 1, 1)
        self.lbl31 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl31.setFont(font)
        self.lbl31.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl31.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl31.setObjectName("lbl31")
        self.grid1.addWidget(self.lbl31, 3, 1, 1, 1)
        self.lbl03 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl03.setFont(font)
        self.lbl03.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl03.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl03.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl03.setObjectName("lbl03")
        self.grid1.addWidget(self.lbl03, 0, 3, 1, 1)
        self.lbl21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl21.setFont(font)
        self.lbl21.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl21.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl21.setObjectName("lbl21")
        self.grid1.addWidget(self.lbl21, 2, 1, 1, 1)
        self.lbl12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl12.setFont(font)
        self.lbl12.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl12.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl12.setObjectName("lbl12")
        self.grid1.addWidget(self.lbl12, 1, 2, 1, 1)
        self.lbl00 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl00.setFont(font)
        self.lbl00.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl00.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl00.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl00.setObjectName("lbl00")
        self.grid1.addWidget(self.lbl00, 0, 0, 1, 1)
        self.lbl22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl22.setFont(font)
        self.lbl22.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl22.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl22.setObjectName("lbl22")
        self.grid1.addWidget(self.lbl22, 2, 2, 1, 1)
        self.lbl32 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl32.setFont(font)
        self.lbl32.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl32.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl32.setObjectName("lbl32")
        self.grid1.addWidget(self.lbl32, 3, 2, 1, 1)
        self.lbl10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl10.setFont(font)
        self.lbl10.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl10.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl10.setObjectName("lbl10")
        self.grid1.addWidget(self.lbl10, 1, 0, 1, 1)
        self.lbl23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl23.setFont(font)
        self.lbl23.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl23.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl23.setObjectName("lbl23")
        self.grid1.addWidget(self.lbl23, 2, 3, 1, 1)
        self.lineA = QtWidgets.QFrame(self.centralwidget)
        self.lineA.setGeometry(QtCore.QRect(530, 250, 105, 3))
        self.lineA.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineA.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineA.setObjectName("lineA")
        self.LineD = QtWidgets.QFrame(self.centralwidget)
        self.LineD.setGeometry(QtCore.QRect(580, 450, 105, 3))
        self.LineD.setFrameShape(QtWidgets.QFrame.HLine)
        self.LineD.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LineD.setObjectName("LineD")
        self.lineB = QtWidgets.QFrame(self.centralwidget)
        self.lineB.setGeometry(QtCore.QRect(520, 260, 3, 85))
        self.lineB.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineB.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineB.setObjectName("lineB")
        self.lineC = QtWidgets.QFrame(self.centralwidget)
        self.lineC.setGeometry(QtCore.QRect(750, 310, 3, 85))
        self.lineC.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineC.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineC.setObjectName("lineC")
        self.a = QtWidgets.QLabel(self.centralwidget)
        self.a.setGeometry(QtCore.QRect(570, 220, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.a.setFont(font)
        self.a.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.a.setFrameShadow(QtWidgets.QFrame.Raised)
        self.a.setAlignment(QtCore.Qt.AlignCenter)
        self.a.setObjectName("a")
        self.b = QtWidgets.QLabel(self.centralwidget)
        self.b.setGeometry(QtCore.QRect(490, 290, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.b.setFont(font)
        self.b.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.b.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b.setAlignment(QtCore.Qt.AlignCenter)
        self.b.setObjectName("b")
        self.c = QtWidgets.QLabel(self.centralwidget)
        self.c.setGeometry(QtCore.QRect(760, 340, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.c.setFont(font)
        self.c.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.c.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c.setAlignment(QtCore.Qt.AlignCenter)
        self.c.setObjectName("c")
        self.d = QtWidgets.QLabel(self.centralwidget)
        self.d.setGeometry(QtCore.QRect(620, 450, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.d.setFont(font)
        self.d.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.d.setFrameShadow(QtWidgets.QFrame.Raised)
        self.d.setAlignment(QtCore.Qt.AlignCenter)
        self.d.setObjectName("d")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(240, 350, 100, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 211, 211, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.btnClear.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnClear.setFont(font)
        self.btnClear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClear.setAutoFillBackground(False)
        self.btnClear.setObjectName("btnClear")
        self.btnNeg = QtWidgets.QPushButton(self.centralwidget)
        self.btnNeg.setGeometry(QtCore.QRect(350, 280, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnNeg.setFont(font)
        self.btnNeg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNeg.setObjectName("btnNeg")
        self.btnRe = QtWidgets.QPushButton(self.centralwidget)
        self.btnRe.setGeometry(QtCore.QRect(350, 350, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnRe.setFont(font)
        self.btnRe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRe.setObjectName("btnRe")
        Karnaugh.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Karnaugh)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        Karnaugh.setStatusBar(self.statusbar)

        self.retranslateUi(Karnaugh)
        QtCore.QMetaObject.connectSlotsByName(Karnaugh)
        Karnaugh.setTabOrder(self.btnA, self.btnB)
        Karnaugh.setTabOrder(self.btnB, self.btnC)
        Karnaugh.setTabOrder(self.btnC, self.btnD)
        Karnaugh.setTabOrder(self.btnD, self.btnPlus)
        Karnaugh.setTabOrder(self.btnPlus, self.btnNeg)
        Karnaugh.setTabOrder(self.btnNeg, self.btnCalc)
        Karnaugh.setTabOrder(self.btnCalc, self.btnClear)

    def retranslateUi(self, Karnaugh):
        _translate = QtCore.QCoreApplication.translate
        Karnaugh.setWindowTitle(_translate("Karnaugh", "Karnaugh-Chart"))
        self.btnA.setText(_translate("Karnaugh", "a"))
        self.btnB.setText(_translate("Karnaugh", "b"))
        self.btnC.setText(_translate("Karnaugh", "c"))
        self.btnD.setText(_translate("Karnaugh", "d"))
        self.btnCalc.setText(_translate("Karnaugh", "Calculate", "Calculates the result."))
        self.btnPlus.setText(_translate("Karnaugh", "+"))
        self.lblHead1.setText(_translate("Karnaugh", "Input:"))
        self.lblHead2.setText(_translate("Karnaugh", "Output (minimized):"))
        self.lbl30.setText(_translate("Karnaugh", "0"))
        self.lbl02.setText(_translate("Karnaugh", "0"))
        self.lbl01.setText(_translate("Karnaugh", "0"))
        self.lbl11.setText(_translate("Karnaugh", "0"))
        self.lbl33.setText(_translate("Karnaugh", "0"))
        self.lbl13.setText(_translate("Karnaugh", "0"))
        self.lbl20.setText(_translate("Karnaugh", "0"))
        self.lbl31.setText(_translate("Karnaugh", "0"))
        self.lbl03.setText(_translate("Karnaugh", "0"))
        self.lbl21.setText(_translate("Karnaugh", "0"))
        self.lbl12.setText(_translate("Karnaugh", "0"))
        self.lbl00.setText(_translate("Karnaugh", "0"))
        self.lbl22.setText(_translate("Karnaugh", "0"))
        self.lbl32.setText(_translate("Karnaugh", "0"))
        self.lbl10.setText(_translate("Karnaugh", "0"))
        self.lbl23.setText(_translate("Karnaugh", "0"))
        self.a.setText(_translate("Karnaugh", "a"))
        self.b.setText(_translate("Karnaugh", "b"))
        self.c.setText(_translate("Karnaugh", "c"))
        self.d.setText(_translate("Karnaugh", "d"))
        self.btnClear.setText(_translate("Karnaugh", "Clear", "Calculates the result."))
        self.btnNeg.setText(_translate("Karnaugh", "¬"))
        self.btnRe.setText(_translate("Karnaugh", "←"))


        #SELF-DEFINED

        self.btnA.clicked.connect(self.clickA)
        self.btnB.clicked.connect(self.clickB)
        self.btnC.clicked.connect(self.clickC)
        self.btnD.clicked.connect(self.clickD)
        self.btnClear.clicked.connect(self.clickCl)
        self.btnCalc.clicked.connect(self.clickCalc)
        self.btnPlus.clicked.connect(self.clickPl)
        self.btnNeg.clicked.connect(self.clickNe)
        self.btnRe.clicked.connect(self.clickRe)

    def clickA(self):
        self.lblInput.setText(self.lblInput.text() + "a")
    
    def clickB(self):
        self.lblInput.setText(self.lblInput.text() + "b")

    def clickC(self):
        self.lblInput.setText(self.lblInput.text() + "c")
    
    def clickD(self):
        self.lblInput.setText(self.lblInput.text() + "d")

    def clickPl(self):
        self.lblInput.setText(self.lblInput.text() + "+")

    def clickNe(self):
        self.lblInput.setText(self.lblInput.text() + "¬")
    
    def clickRe(self):
        self.lblInput.setText(self.lblInput.text()[:-1])
    
    def clickCl(self):
        self.lblInput_2.setText("")
        self.lblInput.setText("")
        self.lbl00.setText("0")
        self.lbl01.setText("0")
        self.lbl02.setText("0")
        self.lbl03.setText("0")
        self.lbl10.setText("0")
        self.lbl11.setText("0")
        self.lbl12.setText("0")
        self.lbl13.setText("0")
        self.lbl20.setText("0")
        self.lbl21.setText("0")
        self.lbl22.setText("0")
        self.lbl23.setText("0")
        self.lbl30.setText("0")
        self.lbl31.setText("0")
        self.lbl32.setText("0")
        self.lbl33.setText("0")
        print("\033[42m\033[30mKARNAUGH: Clearing successfully done.\033[0m")

    def clickCalc(self):
        self.lblInput_2.setText("")
        input = self.lblInput.text()
        input = input.replace("¬", "-")
        input = re.sub("\--","",input)
        for i in range(len(input)):
            if input[i] == "+" and input[i-1] == "-": #checks syntax e.g "abc-+c" is not allowed
                self.lblInput.setText("")
            if input[i] == "+" and input[i-1] == "+":
                self.lblInput.setText("")
        if input[len(input)-1] != "-" and input[len(input)-1] != "+" and input[0] != "+" and self.lblInput.text() != "":
            out = karnaugh.main(input)
            table = karnaugh.retTable(input)
            for i in range(len(out)):
                self.lblInput_2.setText(self.lblInput_2.text() + str(out[i]))
                if i != len(out) - 1:
                    self.lblInput_2.setText(self.lblInput_2.text() + "+")
                self.lblInput_2.setText(self.lblInput_2.text().replace("-","¬"))
            self.lbl00.setText(str(table[0][0]))
            self.lbl01.setText(str(table[0][1]))
            self.lbl02.setText(str(table[0][2]))
            self.lbl03.setText(str(table[0][3]))
            self.lbl10.setText(str(table[1][0]))
            self.lbl11.setText(str(table[1][1]))
            self.lbl12.setText(str(table[1][2]))
            self.lbl13.setText(str(table[1][3]))
            self.lbl20.setText(str(table[2][0]))
            self.lbl21.setText(str(table[2][1]))
            self.lbl22.setText(str(table[2][2]))
            self.lbl23.setText(str(table[2][3]))
            self.lbl30.setText(str(table[3][0]))
            self.lbl31.setText(str(table[3][1]))
            self.lbl32.setText(str(table[3][2]))
            self.lbl33.setText(str(table[3][3]))
            print("\033[42m\033[30mKARNAUGH: Calculating successfully done.\033[0m")
        else:
            self.lblInput.setText("")
            print("\033[41m\033[30mError. No valid input.\033[0m")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Karnaugh = QtWidgets.QMainWindow()
    ui = Ui_Karnaugh()
    ui.setupUi(Karnaugh)
    Karnaugh.show()
    sys.exit(app.exec_())
